name: PR Build Check
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Verify npm installation
        run: npm --version

      - name: Install dependencies
        run: npm install --no-frozen-lockfile

      - name: Build project
        run: npm run build
